### ISSUE TITLE
ifdef MACOS_HAS_NO_CLOCK_GETTME

### ISSUE THREAD

**Issue by rurban** [katef/libfsm#160]
this looks like a typo to me `GETTME`, and disabling it leads to a darwin build.
I don't know any darwin with `clock_gettime`, so 
`#if defined(__APPLE__) && defined(__MACH__)` seems to be enough.

**Comment by katef** [comment]
Thank you!

**Comment by sfstewman** [comment]
Good catch on the typo.

macOS 10.12 (Sierra) and later provide their own `clock_gettime`.  I do my libfsm development on macOS, so this directly affects me, and I had to amend my original patch (see #123) after upgrading to avoid conflicting definitions (see #129).

I'm reluctant to cite StackOverflow as any kind of definitive source, but it give the workaround for pre-10.12 and some independent confirmation that `clock_gettime` exists in 10.12+ 
https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

**Comment by katef** [comment]
https://github.com/katef/libfsm/commit/e5c6b65b81ac657da3cdf3dda6c461cedb144394

I left the macro there, just because I can't be sure there's no system where that is defined. @silentbicycle did you have that situation?
