### ISSUE TITLE
Read lx man pages without installing

### ISSUE THREAD

**Issue by tekknolagi** [katef/libfsm#261]
I see `man/lx.{1,5}/lx.{1,5}.xml` but I don't see anything in the `build/` folder for the generated man pages, nor can I quickly find the build rule to generate them. I'd like to read them -- how should I go about this?

**Comment by katef** [comment]
These should be rendered out to roff (and html etc), and all the build system stuff for that is missing.

I put quite a bit of work into my own rendering stuff (you can see the output for the docs on tendra.org), and I'd like to use those here too. But setting that up is super annoying.

Until that's done, I think it'd make sense to render these (at least to roff) using the stock docbook xslt or whatever's convenient. That just needs adding to the makefiles somehow.

**Comment by katef** [comment]
I added `make doc` for this. The docbook roff rendering is rubbish, but it's all we have for the moment.

**Comment by tekknolagi** [comment]
Whoa, throwback. Nice
