### ISSUE TITLE
Very large image with re

### ISSUE THREAD

**Issue by kyclark** [katef/libfsm#276]
First off, this is an amazing program! Thank you for making it.

When I try to graph the following pattern[1]:

re -cb -pl dot 'N[^P][ST][^P]' | dot -Tpng -ore.png

I get an extremely long image. Is this just the nature of this re or am I doing something wrong?

[1] N-glycosylation protein motif, cf. http://rosalind.info/problems/mprt/

**Comment by sfstewman** [comment]
Hi @kyclark.  If you omit the `-c`, the image gets considerably smaller.

```
./build/bin/re -b -pl dot 'N[^P][ST][^P]' | dot -Tpng > t.png
```

Gives:
![image](https://user-images.githubusercontent.com/2184720/97488764-0dc66900-1935-11eb-8a95-9d3180afcca3.png)

**Comment by kyclark** [comment]
Thanks!
