### ISSUE TITLE
Handling for octal-style group numbering in pcre

### ISSUE THREAD

**Issue by katef** [katef/libfsm#335]
pcre has a parse ambiguity for octal literals vs. backreferences. We don't want to support backreferences (except possibly in the AST), but I would like to handle octal escapes. `\7` means a backreference _iff_ the group exists, and an octal literal otherwise.

To do this, I picture the lexical token being conditionally replaced during parse (as we do for `TOK_MAYBE_COMMENT`), right after being fetched from the lexer. This depends on knowing how many groups exist so far.

Groups are numbered by their opening parentheses. Currently the numbering is done in ast_analysis.c, as a pass after the AST is constructed.

I think the numbering should move on-the-fly into the parser, as part of the parser state. This would probably remove `struct analysis_env` too. Then we have enough information for the conditional on whether the lexical token is supposed to represent a backreference or a literal.

**Comment by sfstewman** [comment]
It's slightly more complex than this.  `\7` always indicates a backreference.

See: http://www.pcre.org/current/doc/html/pcre2pattern.html#SEC5

> The handling of a backslash followed by a digit other than 0 is complicated, and Perl has changed over time, causing PCRE2 also to change.

> Outside a character class, PCRE2 reads the digit and any following digits as a decimal number. If the number is less than 10, begins with the digit 8 or 9, or if there are at least that many previous capture groups in the expression, the entire sequence is taken as a backreference. A description of how this works is given later, following the discussion of parenthesized groups. Otherwise, up to three octal digits are read to form a character code.
