### ISSUE TITLE
Trying to build `libfsm` with a naked `pmake` hangs.

### ISSUE THREAD

**Issue by sw17ch** [katef/libfsm#361]
I had expected `pmake` to produce something, but it hung. I applied `strace` to the build, and found that it was hanging on `sed`. After reading, I realized that the `$PREFIX` is needed to make progress. Is this expected? Could it be made to emit an error instead of hanging?

**Comment by moon-chilled** [comment]
`pmake -r`

**Comment by katef** [comment]
This happens when -r is absent because that brings in the stock sys.mk stuff. I added a guard in 8552cd754bb1aeefaaabe898e0c6d75ba27dd654, which bails out with an error when sys.mk is present. Thanks for the idea!
