### ISSUE TITLE
Clarification needed README instructions re: pmake/bmake on mac

### ISSUE THREAD

**Issue by xandhiller** [katef/libfsm#366]
Regarding the instructions in the README

> To build and install:
> ```
> ; pmake -r install
> ```
> To build on Linux, you may need to install `bmake`, and use it instead of `pmake` in the commands mentioned here.

I had to use `bmake` on Mac too, might want to append this instuction here with that info. Took me ten minutes to try that and I'd like to save someone else the same trouble.

**Comment by katef** [comment]
Thanks! You're right, I definitely should explain this more clearly. The trouble is there are a bunch of different BSD make packages around, and for some bewildering reason they all go by different names. And the makefiles _should_ work with all of them. But the name is whatever the package maintainer gave it! I'm really not sure how to explain that in the readme. I guess I just need the same section talking about bmake per-OS for every project.

**Comment by katef** [comment]
What do you think?
https://github.com/katef/libfsm/pull/376
