### ISSUE TITLE
lexing for pcre comments is slightly incorrect

### ISSUE THREAD

**Issue by katef** [katef/libfsm#417]
/src/dialect/pcre/lexer.lx says:
```
    # emit a token if the comment has nested parens (which are not permitted)
    '(' -> $invalid__comment;
```
this is incorrect, pcregrep allows:
```
; echo x | pcregrep '(?#...(abc)x'
x
```
pcre2syntax(5) says:
```
         (?#....)        comment (not nestable)
```
so i think we should dissallow `'(?#'` specifically here, and allow `(`

**Comment by silentbicycle** [comment]
`pcrepattern` also says (emphasis mine):

> # COMMENTS
> ...
> The sequence (?# marks the start of a comment that continues up to the next closing parenthesis. **Nested parentheses        are not permitted.**

...which to me sounds like it's a bug in PCRE / pcregrep that it's accepted, not a bug in libfsm that it isn't -- nested _parentheses_ specifically are not allowed, not just nested comments. Thoughts?

**Comment by katef** [comment]
Agreed, would you mind commenting that please?
