### ISSUE TITLE
lx: Bus error/Segmentation Fault on malformed input

### ISSUE THREAD

**Issue by cinco-de-mayonnaise** [katef/libfsm#451]
## Describe the bug
Bus Error(core dumped) when `Ix` is executed without any arguments and numbers are typed in

## To Reproduce
Open the console and...
`; lx`
And then type some numbers in. ... yeah that's it.

## Expected behavior
Should it crash?

## Screenshots
![Screenshot from 2023-12-03 01-11-00](https://github.com/katef/libfsm/assets/124304231/8d492e14-bf17-4b9f-86f2-4833974f96bc)

## Environment
OS: Ubuntu 22.04.3 LTS x86_64 
Kernel: 6.2.0-37-generic 
Shell: bash 5.1.16

**Comment by katef** [comment]
> Should it crash?

Absolutely not! Thanks for the bug report!

Possibly related to #351

**Comment by katef** [comment]
#351 is unrelated as far as I can see.
