### ISSUE TITLE
`fsm -t minimise` changes the meaning of some FSMs

### ISSUE THREAD

**Issue by edk0** [katef/libfsm#56]
`re(1)` is affected too. Manually performing the same steps seems not to be.

The smallest testcase I know is (pcre or native) `/[aBx]*a/` (or its equivalent NFA).

**Comment by katef** [comment]
`[aB]*a` shows our bug; `[ab]*a` does not.

**Comment by katef** [comment]
This .fsm reproduces the bug for both `b` and `B`:
```
0->1 'a';
0->1 'B'; # also 'b'
0->1;
1->0;
1->2 'a';
start: 0;
end: 2;
```

**Comment by katef** [comment]
As of 44fb58bfc9ea7b828d8fe229a041aa822475bef4:

`[aBx]*a`
![image](https://user-images.githubusercontent.com/1371085/30242906-a6bea20a-9597-11e7-8b31-c9891d2055e7.png)

`[aB]*a`:
![image](https://user-images.githubusercontent.com/1371085/30242914-d05936de-9597-11e7-848e-c49f817ce0d3.png)
