### ISSUE TITLE
Introduce AST for libre

### ISSUE THREAD

**Issue by katef** [katef/libfsm#82]
Currently libre constructs an NFA directly during parse. This ticket is to introduce an AST between parsing and NFA construction:
* Parser actions construct AST nodes
* The AST expresses whichever syntactic constructs fit most naturally; I would expect nodes for `|` alts and other operators. For some things, the parser can still normalise to a single internal form - "count x..y" repetition for example, where the regexp `a*` syntax is just sugar for `x..y` in general. I'm not currently sure if character classes would be present in the AST directly.

This provides a few possibilities:
* We can transform the AST in various ways, for optimisations which are cheaper than operating on an FSM datastructure
* Output of the AST (including perhaps to regexp syntax)
* Some parts are awkward during parsing, due to the LL(1) recursive descent. Constructing an AST should make those more natural.

**Comment by silentbicycle** [comment]
This should be covered by #89, right?

**Comment by katef** [comment]
Yes - Thank you!
